jwt:
  public:
    key: classpath:app.pubKey
  private:
    key: classpath:app.privKey
spring:
  application:
    name: testContainersApplication
  datasource:
    url: # your database url
    username: # your username
    password: # your password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

