jwt:
  public:
    key: classpath:app.pubKey
  private:
    key: classpath:app.privKey
spring:
  application:
    name: testContainersApplication
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/testContainers?createDatabaseIfNotExist=true
    username: UserJava
    password: UserJava@
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

